on:
  workflow_call:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest-4-cores
    strategy:
      matrix:
        include:
          - model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
            model_tag_name: cross-encoder-ms-marco-MiniLM-L-6-v2
          - model_name: cross-encoder/ms-marco-TinyBERT-L-2-v2
            model_tag_name: cross-encoder-ms-marco-TinyBERT-L-2-v2
          - model_name: cross-encoder/ms-marco-MiniLM-L-2-v2
            model_tag_name: cross-encoder-ms-marco-MiniLM-L-2-v2
          - model_name: BAAI/bge-reranker-v2-m3
            model_tag_name: baai-bge-reranker-v2-m3
    env:
      LOCAL_REPO: reranker-transformers
      REMOTE_REPO: semitechnologies/reranker-transformers
      MODEL_NAME: ${{matrix.model_name}}
      MODEL_TAG_NAME: ${{matrix.model_tag_name}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip' # caching pip dependencies
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and test
        run: |
          cicd/build.sh
          cicd/test.sh
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags')
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          cicd/docker_push.sh
  build-custom-image:
    name: Build custom image
    runs-on: ubuntu-latest
    env:
      LOCAL_REPO: reranker-transformers
      REMOTE_REPO: semitechnologies/reranker-transformers
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build custom image
        run: cicd/build_custom_base.sh
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags')
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: cicd/docker_push_custom_base.sh
